[[plugin]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '~/.pyenv/shims/python3'
'''

[[plugin]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugin]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugin]]
repo = 'Flake8-vim'
on_ft = ['python']
hook_add = '''
    let g:PyFlakeOnWrite = 1
    let g:PyFlakeChekers = 'pep8,mccabe,pyflakes'
    let g:PyFlakeDefaultComplexity=10
'''

[[plugin]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugin]]
repo = 'scrooloose/syntastic'
on_ft = ['python']
hook_add = '''
    let g:syntastic_python_checkers  = ['pyflakes', 'pep8']
'''
