[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
    " racerバイナリ指定
    let g:racer_cmd = expand('~/.cargo/bin/racer')
    " rust本体ソースコードパス指定
    let $RUST_SRC_PATH="/home/pirate/repository/rust/src"
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#rust#racer_binary='/home/pirate/.cargo/bin/racer'
    let g:deoplete#sources#rust#rust_source_path='/home/pirate/repository/rust/src'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K <plug>DeopleteRustShowDocumentation
'''
